### ISSUE TITLE
parallel warning

### ISSUE THREAD

**Issue by markxx010** [airsplay/lxmert#17]
/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
   
Do you have this problem?torch=1.0.1，Whether it affects the final result？

**Comment by airsplay** [comment]
Short Answer: It's OK.

Long Answer: It is because the loss (total_loss) is averaged to a scalar [here](https://github.com/airsplay/lxmert/blob/5caa14ee1094819f00bd45bebf386653af008ee3/src/lxrt/modeling.py#L1039).

The default data_parallel behavior of PyTorch requires a tensor of shape [Batch_size, ...] as module's output and it would concatenate all the tensors w.r.t the first dimension. E.g., It will output a tensor of shape [batch_size * 4, ...] if there are 4 GPUs.

Thus the warning says that the total_loss is scalar (of shape []), thus it will squeeze it (to shape [1]) and concatenate them on the first dimension (result in a tensor of shape [4] if there are 4 GPUs).

**Comment by markxx010** [comment]
got it, thanks
