### ISSUE TITLE
pretrained only on GQA dataset

### ISSUE THREAD

**Issue by alibabadoufu** [airsplay/lxmert#18]
Hi, have you tried pretraining only on the GQA dataset and use the pretrained model to test on the GQA task? The purpose of this might be to test how effective the extra data helps for the specific task such as GQA and also how "powerful" your model is to extract the relationship between 2 modalities.

**Comment by alibabadoufu** [comment]
If you have tested could you roughly remember how good the performance is on the testdev split?

**Comment by airsplay** [comment]
Hi, 

By setting a if conditional `sents_cat == 'gqa'` [here](https://github.com/airsplay/lxmert/blob/965ebe5839e232ee3d0661eee21964c3aa5e4eae/src/pretrain/lxmert_data.py#L117), the model could be pre-trained with GQA only. 

I am sorry that I am currently running out of computational resources in my school thus might not be able to test this on my servers. 

By the way, since GQA is machine-generated instructions (instead of human-written in VQA / NLVR2), it might be possible to see that the fine-tuned results get improved with GQA-only pre-training. Using VQA as benchmarking might be better because of the smaller size and its natural-language questions.
