### ISSUE TITLE
Low training speed

### ISSUE THREAD

**Issue by ypengc7512** [airsplay/lxmert#30]
Thanks for your excellent work. When I tried to run the code you provided, I found that each epoch would take 28 hours on 8 2080Ti GPUs. However, you mentioned that it takes only 19 hours per epoch on 4 Titan XP GPUs in the previous issue. Do you think there is any reason why the current training is too slow?

![image](https://user-images.githubusercontent.com/25523342/69002306-99fb9e00-0927-11ea-99a7-4ef90ef76deb.png)

**Comment by airsplay** [comment]
May I ask for the batch-size of the pre-training? Otherwise, the bottleneck might be the IO loading (Memory efficiency) and I could pack some updates if needed. 

By the way, since I repeated VQA&MSCOCO to balance the amount of data in the previous experiment, the amount of data is increased. The speed of one epoch should be around 12 hours and is around 10~11 hours on Titan V when using the default setup.
