### ISSUE TITLE
Dev-set splits in paper

### ISSUE THREAD

**Issue by j-min** [airsplay/lxmert#54]
Hi,

Could you please specify which dev-set splits you used to obtain scores below in the paper?
Ex) Are VQA dev-set accuracy below from VQA test-dev split? or are they from MSCOCO minival? And which splits are used in GQA/NLVR?

![image](https://user-images.githubusercontent.com/18069263/80654660-aa18bd00-8a31-11ea-8a8c-0b43281e6dc6.png)

![image](https://user-images.githubusercontent.com/18069263/80654668-aedd7100-8a31-11ea-9adc-6b5c9c4bb1ed.png)

**Comment by airsplay** [comment]
Thanks. The dev-set of VQA is the minival set. Since the paper only compares with itself in this table, the tendency should be valid.  The test-dev result is 72.42%.

GQA is the test-dev. However, I calculate the top-1 accuracy for simplicity (as provided in this code). Thus the score would be different (usually higher) when submitting to the GQA test server, which seems to consider synonyms. 

NLVR2 is just the valid set.

**Comment by j-min** [comment]
Thanks for the clarification :)
