### ISSUE TITLE
GPU out of memory error

### ISSUE THREAD

**Issue by mehrdad-h** [airsplay/lxmert#6]
Hi,

I just ran the docker for feature extractor on COCO, but I hit an error saying out of memory: 

`/opt/butd//tools/../lib/rpn/proposal_layer.py:27: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  layer_params = yaml.load(self.param_str)
  0%|          | 0/82783 [00:00<?, ?it/s]WARNING: Logging before InitGoogleLogging() is written to STDERR
F0829 23:53:49.776543   146 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Aborted
root@eb7c95126dbc:/workspace/features# 
`

It's weird because I'm watching my GPU and it only uses  ~ 2GB (out of 8GB). But it still throws me an out-of-memory error. It even happens when I set `BATCH_SIZE` to 2 in the config file. Any thought?

**Comment by airsplay** [comment]
Hi,

Short Answer:
Please add these first two lines to `faster_rcnn_end2end_resnet.yml` under `TEST:`
```
TEST:
  SCALES: [300,]
  MAX_SIZE: 400
  HAS_RPN: True
  HAS_ATTRIBUTES: True
  HAS_RELATIONS: False
  SOFT_NMS: 0
```

Long Answer:
Faster R-CNN is single batched when testing, thus the batch size would not affect the memory usage. And it uses a large size of image (i.e., short edge >= 600, long edge <= 1000 instead of (224, 224) in ResNet) in order to capture small objects.
To save memory, the current solution I came up with is to reduce the size of the image. The first two lines are for this purpose. 

More descriptions of the config file are [here](https://github.com/peteanderson80/bottom-up-attention/blob/master/lib/fast_rcnn/config.py).

Hope it helps!

**Comment by airsplay** [comment]
I tested it on NLVR2. It works with a little bit drop in the result.
